// lib/ayurveda/recipes.js

/**
 * Minimal curated set for planning (Phase 2 seed dataset).
 * Each recipe includes Ayurvedic tags so we can do:
 * dosha + season + health goal + mood + pantry match.
 */

export const AYURVEDIC_RECIPES = [
  {
    id: "moong-dal-khichdi",
    title: "Moong Dal Khichdi",
    ingredients: ["rice", "moong dal", "ghee", "cumin", "turmeric", "ginger", "salt"],
    seasons: ["rainy", "winter", "autumn"],
    qualities: ["warming", "easy_digest", "grounding"],
    doshaBalance: ["vata", "pitta", "kapha"],
    goals: ["digestion", "energy", "weight_loss"],
    moods: ["low_energy", "stress", "feeling_cold"],
  },
  {
    id: "vegetable-upma",
    title: "Vegetable Upma",
    ingredients: ["semolina", "ghee", "mustard seeds", "curry leaves", "ginger", "carrot", "peas", "salt"],
    seasons: ["winter", "spring", "rainy"],
    qualities: ["warming", "light"],
    doshaBalance: ["vata", "kapha"],
    goals: ["energy", "weight_loss"],
    moods: ["low_energy", "feeling_cold"],
  },
  {
    id: "lemon-rice",
    title: "Lemon Rice",
    ingredients: ["rice", "lemon", "peanuts", "mustard seeds", "turmeric", "curry leaves", "salt"],
    seasons: ["spring", "autumn"],
    qualities: ["light"],
    doshaBalance: ["kapha"],
    goals: ["energy", "weight_loss"],
    moods: ["low_energy"],
  },
  {
    id: "buttermilk-spiced",
    title: "Spiced Buttermilk (Chaas)",
    ingredients: ["buttermilk", "cumin", "coriander", "mint", "salt"],
    seasons: ["summer", "autumn"],
    qualities: ["cooling", "digestive", "light"],
    doshaBalance: ["pitta", "kapha"],
    goals: ["digestion", "weight_loss"],
    moods: ["stress"],
  },
  {
    id: "cucumber-mint-raita",
    title: "Cucumber Mint Raita",
    ingredients: ["yogurt", "cucumber", "mint", "cumin", "salt"],
    seasons: ["summer", "autumn"],
    qualities: ["cooling", "hydrating"],
    doshaBalance: ["pitta"],
    goals: ["digestion", "diabetes_friendly"],
    moods: ["stress"],
  },
  {
    id: "millet-porridge",
    title: "Millet Porridge with Ghee",
    ingredients: ["millets", "ghee", "milk", "cardamom"],
    seasons: ["winter"],
    qualities: ["warming", "grounding"],
    doshaBalance: ["vata"],
    goals: ["energy", "weight_loss"],
    moods: ["low_energy", "feeling_cold"],
  },
  {
    id: "vegetable-soup",
    title: "Warming Vegetable Soup",
    ingredients: ["carrot", "pumpkin", "ginger", "black pepper", "salt", "ghee"],
    seasons: ["winter", "rainy"],
    qualities: ["warming", "light"],
    doshaBalance: ["vata", "kapha"],
    goals: ["digestion", "weight_loss", "diabetes_friendly"],
    moods: ["feeling_cold", "stress"],
  },
  {
    id: "jeera-rice",
    title: "Jeera (Cumin) Rice",
    ingredients: ["rice", "cumin", "ghee", "salt"],
    seasons: ["rainy", "winter", "spring"],
    qualities: ["digestive", "light"],
    doshaBalance: ["vata", "kapha"],
    goals: ["digestion", "energy"],
    moods: ["low_energy"],
  },
  {
    id: "turmeric-ginger-tea",
    title: "Turmeric Ginger Tea",
    ingredients: ["ginger", "turmeric", "black pepper", "water", "lemon"],
    seasons: ["winter", "rainy", "spring"],
    qualities: ["warming", "digestive"],
    doshaBalance: ["kapha", "vata"],
    goals: ["digestion", "energy", "diabetes_friendly"],
    moods: ["feeling_cold", "stress"],
  },
  {
    id: "coconut-chutney",
    title: "Coconut Chutney",
    ingredients: ["coconut", "curry leaves", "mustard seeds", "salt", "ginger"],
    seasons: ["summer", "autumn"],
    qualities: ["cooling"],
    doshaBalance: ["pitta", "vata"],
    goals: ["energy"],
    moods: ["stress"],
  },
];

